# Avoid long parameter lists
Style/ParameterLists:
  Max: 3
  CountKeywordArgs: true

Style/MethodLength:
  CountComments: false
  Max: 15

Style/ClassLength:
  CountComments: false
  Max: 100

Style/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Style/BlockNesting:
  Max: 3

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/IndentHash:
  EnforcedStyle: consistent

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  ()
    '%i': ()
    '%q': ()
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': '[]'
    '%W': '[]'
    '%x': ()

Style/Encoding:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

# New lambda syntax is UGLY, don't enforce it
Style/LambdaCall:
  EnforcedStyle: braces

AllCops:
  Include:
    - Gemfile
  Exclude:
    - 'spec/spec_helper.rb'
    - 'spec/support/**'
